### ISSUE TITLE
Avoid confusion with the Sourceforge repository

### ISSUE THREAD

**Issue by ao2** [PHPCheckstyle/phpcheckstyle#55]
Hi,

AFAIU the main repository for PHPCheckstyle is the one on sourceforge: https://sourceforge.net/projects/phpcheckstyle/

This is not immediately clear from the github page, and the user may end up fetching some outdated code with git, at least compared with the code fetched by composer.

Can you please try to improve this situation?

Thanks.

**Comment by jbrooksuk** [comment]
IIRC we spoke with @tchule about moving here, but he chose not to :)

I guess this repo can be closed.

In the meantime, I started a new project called [Hippo](https://github.com/HippoPHP/Hippo) which should be faster and allows more in-depth checks.

**Comment by ao2** [comment]
@jbrooksuk  I see, thanks for the prompt reply, closing the project will indeed avoid the confusion.

JFYI, the Drupal project uses an extension to PHP_CodeSniffer (https://github.com/squizlabs/PHP_CodeSniffer) called Coder Sniffer (https://www.drupal.org/node/1419980) to check for its coding standards (https://www.drupal.org/coding-standards).

**Comment by jbrooksuk** [comment]
Alternatively, you can use [StyleCI](https://styleci.io) which is a service I run. It fixes your code automatically for you too (if you want).

**Comment by tchule** [comment]
Sorry for the delay, I've been quite busy.

I've just moved the project here again, to simplify the use of Composer/Packagist.

For now the project is updated on version 0.14.3 (latest from sourceforge).
I'll try to keep it up to date and easy to use but there is not a lot of activity and the project is not yet updated for PHP 7. 

You can check James's project or PHP_CodeSniffer for something more complete.
