### ISSUE TITLE
[Question] Encapsed variable + Single quote preference

### ISSUE THREAD

**Issue by popojargo** [PHPCheckstyle/phpcheckstyle#59]
I would like to make sure that single quotes are preferred but allow the use of double quotes for encapsed variables. Is there a way to allow such a configuration?

**Comment by tchule** [comment]
I havn't tested it for a while, but you should be able to specify the level of error of the "preferQuotes" test.
It should be "warning"by default, you can set it to "info".

<test name="preferQuotes">
		<property name="type" value="single"  level="info" />
</test>

**Comment by popojargo** [comment]
I know that we can change the level but is there a way to create an exception for double quotes? 
The point is, I'm using single quotes by preference because it's more efficient than double quotes.
Therefore, when you have values that need to be printed in a string, it's as much efficient to use double quotes or concatenation.

**Comment by tchule** [comment]
I'm sorry, I'm not sure I understand what you want to do.

You prefer to use single quotes in the code, ok. So PHPCheckstyle should say nothing when it encounters single quotes. When it encounters double quotes, it should raise an error/warning/info. 
That's what the "preferQuotes" check should do. 

Can you provide an example of code with the expected result ?

Thanks,

**Comment by jbrooksuk** [comment]
>  I'm using single quotes by preference because it's more efficient than double quotes.

https://nikic.github.io/2012/01/09/Disproving-the-Single-Quotes-Performance-Myth.html

**Comment by popojargo** [comment]
I think that I will only change the level to info. Thank you for your time guys
