### ISSUE TITLE
Configure reporter level

### ISSUE THREAD

**Issue by JohnnyQQQQ** [PHPCheckstyle/phpcheckstyle#74]
I would like to see in the console only the errors and not the info and warnings. I don't think that it's implemented yet.

I would suggest a CLI Flag for the run.php file like `--level error`

I could contribute up a merge request if this feature would be approved.

**Comment by tchule** [comment]
Sure, feel free to contribute.

Isn't the level for the console the same as the level for the other reporters ? You can configure it via the config files. Do you want to have a different level just for the console ?

**Comment by JohnnyQQQQ** [comment]
Basically I only want to see the level "error" in my CI pipeline and not display all the warnings and infos.

**Comment by tchule** [comment]
OK, I think you can add a flag in run.php and update the console reporter to test for its presence. Should be easy.

If you can do a merge request its perfect.
