### ISSUE TITLE
Cannot define idependent rules for function parameter namings and local variable namings

### ISSUE THREAD

**Issue by dpalic** [PHPCheckstyle/phpcheckstyle#82]
I am trying to integrate phpcheckstyle, sadly I could not find a way to separate two cases:
- function parameter (variable) naming
- local variable naming

We would like to use different namings for local vars and different namings for parameter namings.
In JS and Java checkstyles this is handled independently, since they are also independent levels of definition. Is there a way to solve it in phpcheckstyle?

**Comment by tchule** [comment]
Hello,

For now we don't make the difference. 
We do list the function parameters in a array ($this->_functionParameters), so it may be possible to add a specific rule. I'll have a look we I can find so time.

**Comment by tchule** [comment]
I've commited something to master, there is a new rule "functionParameterNaming".

Can you have a look ?

**Comment by dpalic** [comment]
@tchule great!
Did not expect that fast response and even could not have imagined in my dreams to get the feature implemented.
Big thanks!
Works like charm.
Can I somehow support your project?

**Comment by dpalic** [comment]
sorry correction
code has a issue.
if the parameter is defined and the parameter is reused in code. the Parameter will be considered as a local variable

**Comment by tchule** [comment]
No problem, you can support the projet by continuing testing and reporting mistakes ^^

I always make this error where I mix in_array() and array_key_exists(). I've committed a correction, it should solve the problem.

I can release a new version anytime. If this version works for you, i'll wait one night for Jenkins to run on all my projects and I can make a release.
