### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by prabhakar267** [PHPCheckstyle/phpcheckstyle#83]
I am trying to integrate this in one of my projects. 
Can someone help me to add checkstyle checks in Travis CI

**Comment by tchule** [comment]
Hi,

That's a good question. I was going to reply that the project itself is using Travis CI, but its for the PHPUnit tests only. 

I'll try to see if I can run PHPCheckstyle on itself when I can find some time.

**Comment by prabhakar267** [comment]
If there is no existing infrastructure, I think we can build something on top of ```run.php```, which can throw an exception if any errors / warnings (configurable) for Travis to pick

**Comment by tchule** [comment]
Yes, just tested it on the project itself. 
"run.php" return an error code different of 0 when there is at least an error. Seems to work.
I close the issue and I add an entry in the wiki.
