### ISSUE TITLE
PHP 5.5 Support

### ISSUE THREAD

**Issue by jbrooksuk** [PHPCheckstyle/phpcheckstyle#9]
_Copied from the GoogleCode issues._
- [x] New token: `T_FINALLY`
- [ ] Traits: http://www.php.net/manual/en/language.oop5.traits.php

**Comment by popojargo** [comment]
The short array syntax is generating indentation errors. Your parser is looking for T_ARRAY token array() but doesn't handle the [ ]. Any feasible way we could support the short array syntax?

**Comment by tchule** [comment]
I need to have a look. We use the internal PHP tokenized, so if PHP detects the short array syntax, we should be able to do it too.

**Comment by tchule** [comment]
See https://github.com/PHPCheckstyle/phpcheckstyle/issues/62

**Comment by tchule** [comment]
Could you provide a sample for the indentation problem ? I think I have a fix but i'd like to test it first.

**Comment by popojargo** [comment]
Let's say I have a multiline array like this : 

```php
protected static $codeSubtypes = [
        401 => 'CouchUnauthorizedException',
        403 => 'CouchForbiddenException',
        404 => 'CouchNotFoundException',
        417 => 'CouchExpectationException'
    ];
```

**Comment by tchule** [comment]
I hav'nt been able to produce the indentation errors, do you check to indentation with tabs or spaces ?

```
	<!-- Tests to make sure that a line does not contain the tab character. -->
	<test name="indentation">  <!-- noTabs -->
		<property name="type" value="tabs" /> <!-- tabs or spaces -->
		<property name="number" value="4" /> <!-- number of spaces if type = spaces -->
	</test>
```

**Comment by popojargo** [comment]
Spaces

**Comment by tchule** [comment]
OK, i'll have a look tomorrow, thx.

**Comment by tchule** [comment]
OK, i've tested with your configuration and the multiline array example you provided, and I have some "Tab indentation must not be used." warnings. 
This seems consistent to me, it is not linked to the fact that it is a short array syntax.

But maybe this is not the indentation errors you where seeing, don' t hesitate to complete the example.

**Comment by popojargo** [comment]
I am having this warning : The indentation level must be 4 but was 8.
With the following file : [CouchException.php](https://github.com/popojargo/PHP-on-Couch/blob/feature/mango_query/src/Exceptions/CouchException.php)

If I change the indentation according to the warning, it's just very awful and I have never seen any language with such formatting. 

Also, from what I have seen from the code, the multiline array is possible with the Array token. Therefore, the short array syntax [] is not recognize as array token I think.

**Comment by tchule** [comment]
OK, I understand now.

With your file (and copy/paste from GitHub doesn't work because spaces are replaced by tabs, but downloading the raw file is OK), i've been able to reproduce your problem.

I've commited something that should solve the problem (https://github.com/PHPCheckstyle/phpcheckstyle/commit/5ddeac37c51d1eeb46df224a058a65aa82588c4f).

I will wait the see if there is some regression before to release a new version,  i'd like to complete my unit tests too.
