### ISSUE TITLE
Use Bootstrap4 for styling

### ISSUE THREAD

**Issue by HCrane** [PHPCheckstyle/phpcheckstyle#93]
Hey guys! 

Big fan of your codestyle-checker. Only thing is that it is quite hard in big projects to distinguish between "info" and "error" by scrolling through the tables. I did some quickfix for me and included bootstrap into your project which is quite nice for the eyes:

![screenshot_1](https://user-images.githubusercontent.com/10025542/45152587-beaba000-b1d1-11e8-885b-8d335c6ea1dd.png)

**Comment by tchule** [comment]
Hello,

Nice, would you mind sharing your modification ? 
I might update the projet to include it (i need to check if the is no problem with the dependency on Bootstrap).

Thanks,

Tchule

**Comment by HCrane** [comment]
Sure! I did edit the `header.tmpl` to include all the files from Bootstrap4s CDN. Rest was just a bit of editing and adding attributes like this in ``. 
```<td class="tableCell" align="center"><span class="badge badge-pill badge-%%level%%">%%level%%</span></td>```
If i were you I would completely ditch the global.css and use bootstrap + custom css file for some self written css classes. By the way the info badge tutorial you can find here: https://getbootstrap.com/docs/4.1/components/badge/#pill-badges

**Comment by tchule** [comment]
OK, i've modified the template. 

So more redesign should be done, to have a cleaner, more modern result page. 
But I'm not the best person for that.
